name: Continuous testing and deployment
on:
  push:
    branches-ignore:
     - 'dependabot/**'
  pull_request:
  update_dispatch:

permissions: read-all

jobs:
  # test:
  #   name: Run tests
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Install goss and dgoss
  #       uses: e1himself/goss-installation-action@v1.0.4
  #       with:
  #         # Goss release version to install
  #         version: 'v0.3.16'

  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Build the Docker image
  #       uses: docker/build-push-action@v3.2.0
  #       with:
  #         push: false
  #         tags: phanan/koel:test

  #     - name: Run goss tests on the image
  #       run: dgoss run phanan/koel:test

  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-20.04
    # needs: [test]
    # if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    permissions:
      contents: read
      packages: write
      attestations: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push the production image
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: ${{ steps.meta.outputs.labels }}
